export const users = {
  data: {
    DieEiseneFaust: {
      email: 'michael.murvine@gmail.com',
      followers: ['thejohnwoz'],
      following: ['thejohnwoz'],
      reviews: 0,
      username: 'DieEiseneFaust',
      __collections__: {},
    },
    Eatthischair: {
      email: 'thomas.stephenson97@gmail.com',
      firstName: 'Thomas',
      followers: [],
      following: [],
      lastName: 'Stephenson',
      profileVisibility: 'Public',
      reviews: 0,
      username: 'Eatthischair',
      __collections__: {},
    },
    Lucawoz3312: {
      email: 'Lucawoz333@gmail.com',
      followers: ['thejohnwoz', 'Milrat45', 'theeasterbunny'],
      following: ['thejohnwoz', 'Milrat45'],
      reviews: 0,
      username: 'Lucawoz3312',
      __collections__: {},
    },
    Milrat45: {
      email: 'Gary.milner45@gmail.com',
      followers: ['thejohnwoz', 'Lucawoz3312', 'theeasterbunny'],
      following: ['thejohnwoz', 'Lucawoz3312'],
      reviews: 0,
      username: 'Milrat45',
      __collections__: {},
    },
    TJTADitXejmQ83HdFqXw: {
      email: 'Tiffanyjoxford@gmail.com',
      followers: [],
      following: [],
      reviews: 0,
      username: '',
      __collections__: {},
    },
    lucawoz123: {
      email: 'Lucawoz123@gmail.com',
      followers: ['thejohnwoz'],
      following: [],
      reviews: 0,
      username: 'lucawoz123',
      __collections__: {},
    },
    qNHPcIsWY607ilRummKC: {
      email: 'Mnadimi09@gmail.com',
      followers: [],
      following: [],
      reviews: 0,
      username: '',
      __collections__: {},
    },
    theeasterbunny: {
      email: 'easterbunny@gmail.com',
      followers: ['thejohnwoz'],
      following: ['thejohnwoz', 'Milrat45', 'Lucawoz3312'],
      reviews: 0,
      username: 'theeasterbunny',
      __collections__: {},
    },
    thejohnwoz: {
      email: 'johnwozniewski@gmail.com',
      firstName: 'John',
      followers: [
        'Lucawoz3312',
        'Milrat45',
        'DieEiseneFaust',
        'theeasterbunny',
      ],
      following: [
        'Lucawoz3312',
        'Milrat45',
        'DieEiseneFaust',
        'lucawoz123',
        'theeasterbunny',
      ],
      lastName: 'Wozniewski ',
      profileVisibility: 'Public',
      reviews: 0,
      username: 'thejohnwoz',
      __collections__: {},
    },
  },
};
